@startuml
title 团长收货

participant 团长端 as 团长端
participant 处理结束 as 处理结束
participant Document as Document

participant 交易侧 as 交易侧
control 死信 as 死信
control 重试 as 重试
database DB as DB
queue MQGroupInStore as MQGroupInStore
queue MQDocument2jiaoyi as MQDocument2jiaoyi

       团长端 -> MQGroupInStore:团长收货
       MQGroupInStore --> Document
       Document -> Document:AllocationGroupHeadReceiptCallbackConsumer

      Document -> Document :checkParam 参数校验
      alt 校验是否通过
           group 通过
           Document -> Document: return
           end
      else
          group 不通过
          Document -> Document: throw ParamException
          Document ->o  处理结束
          end
      end
      Document -> Document:新老单据分组
      Document -> Document:过滤老单据(目前代码上有保留)
     group DB部分
         Document -> DB:查询调拨单
         DB --> Document:return
         Document ->x 死信 :数量不一致throw BizException
         Document -> Document ++: 处理流水handleRecordVos
         Document -> Document ++: 批量构造convertRecordPo
         Document -> Document : 单条构造buildAllocationFulfillmentInOutRecordPo
         Document --> Document --: convertRecordPo return
         Document -> Document ++:计算更新的调拨单状态buildUpdateParamForSameCallBack
         Document -> Document :过滤掉网为操作方的事件变更
         Document -> Document :通过状态机计算每个调拨单的目标状态
         Document -> Document :按照(old-new）分组便于批量处理
         Document --> Document --:buildUpdateParamForSameCallBack return
         Document -> Document ++:针对收货时仓网差异分配不匹配场景的兼容
         Document -> Document: 从待处理列表中取出需要根据流水判断的单据
         Document -> Document: 查询带判断单据的网格站出库流水
         Document ->x 死信: 如果网格站无流水 throw BizException
         Document -> Document: 将需要待处理的调拨单状态改为收货
         Document --> Document --: 差异分配兼容场景处理结束
         Document -> Document:过滤掉已经配送失败的单据的流水和调拨单
         Document -> DB : allocationFulfillmentRepository.saveRecordAndUpdateStatus 保存
         DB --> Document:return
         Document --> Document --:handleRecordVos return
     end
         Document -> MQDocument2jiaoyi: 同步到交易侧
     alt 同步交易侧无异常
         MQDocument2jiaoyi --> 交易侧
      else 有异常
          Document ->x 重试:进入重试表
      end
     Document ->o 处理结束: 处理完成
@enduml